# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hornet-connector-ruby}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Robin Komiwes}, %q{Benjamin Tierny}, %q{Tristan Bourgois}, %q{Maxime Brazeilles}]
  s.date = %q{2011-07-01}
  s.description = %q{Hornet Ruby Connector is a connector for Hornet, a realtime engine backed by Redis and Socket.io}
  s.email = %q{robin.komiwes@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "hornet-connector-ruby.gemspec",
     "init.rb",
     "lib/hornet.rb",
     "test/hornet-connector-ruby_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/nectify/hornet-connector-ruby}
  s.rdoc_options = [%q{--charset=UTF-8}]
  s.require_paths = [%q{lib}]
  s.rubyforge_project = %q{hornet-connector-ruby}
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Hornet Ruby Connector - Realtime engine for webapps}
  s.test_files = [
    "test/hornet-connector-ruby_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<alphadecimal>, [">= 0"])
    else
      s.add_dependency(%q<alphadecimal>, [">= 0"])
    end
  else
    s.add_dependency(%q<alphadecimal>, [">= 0"])
  end
end
